# We also have dkms in the install script.
PACKAGE_NAME="sc0710"
PACKAGE_VERSION="2026.03.13.1"
BUILT_MODULE_NAME[0]="sc0710"
BUILT_MODULE_LOCATION[0]="build/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/media/pci/"
AUTOINSTALL="yes"
MAKE[0]="make KVERSION=$kernelver -j$(nproc)"
